### ISSUE TITLE
Send Custom event with RabbitMQ

### ISSUE THREAD

**Issue by workfel** [vulcainjs/vulcain-corejs#26]
Hello,

I tried to send a custom event from an action. I use the requestContext to send this event.
`this.requestContext.sendCustomEvent` but nothing happen.
When i debug the source code i found  on `requestContext` file :

```js
public sendCustomEvent(action: string, params?: any, schema?: string) {
        if (!action) {
            throw new Error("Action is required for custom event.");
        }
        if (!this._customEvents) {
            this._customEvents = [];
        }
        this._customEvents.push({ action, schema, params });
    }
```
The `_customEvents` property are never used, it's normal ? 

Thx

**Comment by malain** [comment]
In which context (action or query) ?

**Comment by workfel** [comment]
I'm in event . With the `@Consume`

**Comment by malain** [comment]
ok, this was not supported. You can now update to a new corejs version.

**Comment by workfel** [comment]
Ok, thx

**Comment by workfel** [comment]
Now, i have this error after updating the version

```
Error: Error when instanciating component undefined on injected parameter : Unable to resolve component Container
--
  | at Resolver.injectArguments (/opt/app-root/src/node_modules/vulcain-corejs/dist/di/resolvers.js:77:23)
  | at Resolver.resolve (/opt/app-root/src/node_modules/vulcain-corejs/dist/di/resolvers.js:28:14)
  | at Container._resolve (/opt/app-root/src/node_modules/vulcain-corejs/dist/di/containers.js:252:45)
  | at Container.resolve (/opt/app-root/src/node_modules/vulcain-corejs/dist/di/containers.js:249:21)
  | at Function.<anonymous> (/opt/app-root/src/node_modules/vulcain-corejs/dist/commands/command/commandFactory.js:45:49)
  | at next (native)
  | at /opt/app-root/src/node_modules/vulcain-corejs/dist/commands/command/commandFactory.js:7:71
  | at __awaiter (/opt/app-root/src/node_modules/vulcain-corejs/dist/commands/command/commandFactory.js:3:12)
  | at Function.getAsync (/opt/app-root/src/node_modules/vulcain-corejs/dist/commands/command/commandFactory.js:33:16)
  | at RequestContext.getCommandAsync (/opt/app-root/src/node_modules/vulcain-corejs/dist/servers/requestContext.js:140:48)
  | at InvitationEventHandler.createCommandAsync (/opt/app-root/src/node_modules/vulcain-corejs/dist/pipeline/abstractHandlers.js:41:36)
  | at InvitationEventHandler.<anonymous> (/opt/app-root/src/dist/api/handlers/InvitationEventHandler.js:33:53)
  | at next (native)
  | at fulfilled (/opt/app-root/src/dist/api/handlers/InvitationEventHandler.js:13:58)
  | at process._tickCallback (internal/process/next_tick.js:103:7)
```
